# Generated by Django 6.1.1 on 2026-09-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='category',
            field=models.CharField(choices=[('language', 'langage'), ('framework', 'Framework & librairie'), ('tool', 'Outil & méthodologie')], max_length=20),
        ),
    ]
